FROM updated-bionic
#FROM ubuntu:latest
COPY scripts /home/scripts
WORKDIR /home/scripts
RUN ["chmod", "+x", "startup_script_agent.sh"]
ENV KUBE_MASTER_VIP=192.168.168.100
ENV KUBE_MASTER_IP_01=192.168.168.101
ENV KUBE_MASTER_IP_02=192.168.168.102
ENV KUBE_MASTER_IP_03=192.168.168.103
ENV NODE_NETWORK_TYPE=eth0
# RUN ["export", "RUNLEVEL=1"]
 
RUN ["bash","./startup_script_agent.sh"]
 