FROM ubuntu:18.04
 
RUN ["apt-get", "upgrade"] 
RUN ["apt-get", "update"] 
RUN ["apt-get", "install", "-y",  "apt-transport-https", "software-properties-common","net-tools","iputils-ping", "zip", "git","vim", "jq", "curl"]  
RUN ["add-apt-repository", "-y", "ppa:vbernat/haproxy-1.8"] 
RUN ["apt-get", "install", "-y", "--no-install-recommends", "haproxy=1.8.24-1ppa1~bionic","keepalived=1:1.3.9-1ubuntu0.18.04.2"] 
RUN ["apt-mark", "hold", "haproxy", "keepalived"] 
RUN ["apt-get", "-y", "upgrade"] 
RUN ["apt-get", "-y", "update"] 
RUN ["apt-get",  "-y", "autoremove"]  
RUN ["apt-get",  "-y", "autoclean"]  
 